# --- Sorting behavior ---
sorting:
  default_mode: alpha_exact              # only mode we use
  low_confidence_threshold: 0.80         # divert to ERR1 below this
  near_full_threshold: 0.90              # informational; not used for rerouting

# --- Feeder axiom: A-row reserved (A1–A3); never place into these ---
feeder:
  reserve_pattern: "^A\\d+$"

# --- Error/overflow cell(s) ---
overflow:
  cells: [ERR1]                          # first usable is chosen

# --- Manual A–Z mapping (each letter has EXACTLY one destination cell) ---
alpha_exact:
  letter_to_cell:
    A: B1
    B: B2
    C: B3
    D: C1
    E: C2
    F: C3
    G: D1
    H: D2
    I: D3
    J: E1
    K: E2
    L: E3
    M: F1
    N: F2
    O: F3
    P: G1
    Q: G2
    R: G3
    S: H1
    T: H2
    U: H3
    V: I1
    W: I2
    X: I3
    Y: J1
    Z: J2

# --- Physical cells (example grid; rows 1–3 only) ---
cells:
  # Feeders (reserved)
  - { id: A1, capacity: 120, tags: [feeder] }
  - { id: A2, capacity: 120, tags: [feeder] }
  - { id: A3, capacity: 120, tags: [feeder] }

  # Placement cells used in letter_to_cell (must exist)
  - { id: B1, capacity: 60, tags: [] }
  - { id: B2, capacity: 60, tags: [] }
  - { id: B3, capacity: 60, tags: [] }

  - { id: C1, capacity: 60, tags: [] }
  - { id: C2, capacity: 60, tags: [] }
  - { id: C3, capacity: 60, tags: [] }

  - { id: D1, capacity: 60, tags: [] }
  - { id: D2, capacity: 60, tags: [] }
  - { id: D3, capacity: 60, tags: [] }

  - { id: E1, capacity: 60, tags: [] }
  - { id: E2, capacity: 60, tags: [] }
  - { id: E3, capacity: 60, tags: [] }

  - { id: F1, capacity: 60, tags: [] }
  - { id: F2, capacity: 60, tags: [] }
  - { id: F3, capacity: 60, tags: [] }

  - { id: G1, capacity: 60, tags: [] }
  - { id: G2, capacity: 60, tags: [] }
  - { id: G3, capacity: 60, tags: [] }

  - { id: H1, capacity: 60, tags: [] }
  - { id: H2, capacity: 60, tags: [] }
  - { id: H3, capacity: 60, tags: [] }

  - { id: I1, capacity: 60, tags: [] }
  - { id: I2, capacity: 60, tags: [] }
  - { id: I3, capacity: 60, tags: [] }

  - { id: J1, capacity: 60, tags: [] }
  - { id: J2, capacity: 60, tags: [] }

  # Error/overflow
  - { id: ERR1, capacity: 300, tags: [error-pile] }
